### ISSUE TITLE
Add Custom Labels

### ISSUE THREAD

**Issue by harsha-chamarthi** [nleiva/ansible-role-grafana_agent#6]
Add support for custom labels to uniquely identify the source of metrics if you are running multiple Grafana Agents across multiple machines

**Comment by nleiva** [comment]
Could you provide a config example with these labels?

**Comment by harsha-chamarthi** [comment]
https://grafana.com/docs/agent/latest/configuration/metrics-config/#global_config
# A list of static labels to add for all metrics.
external_labels:
  { <string>: <string> }

Add a label, for example environment: dev to differentiate between different environments

**Comment by nleiva** [comment]
Thanks. The current config looks like this:

```yaml
prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs: null
```

Maybe we can make it something like:

```yaml
prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
external_labels:
  { environment : {{ grafana_agent_env | default('dev') }} }
  configs: null
```

And expose the variable `grafana_agent_env`. What do you think?
